name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 主要分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current date (UTC+8)
        id: date
        env: # 設定時區為台北時間 (UTC+8)
          TZ: Asia/Taipei
        run: echo "DATE=$(date +'%Y年%m月%d日 %H:%M:%S') (UTC+8)" >> $GITHUB_OUTPUT 

      - name: Update date in HTML
        run: |
          sed -i "s|<span id=\"last-updated-date\">.*</span>|<span id=\"last-updated-date\">${{ steps.date.outputs.DATE }}</span>|g" ./footer.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' # 確保只在主分支上部署
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # 網站靜態檔案目錄