name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 主要分支名稱

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: # <-- 添加這一段
      contents: write # 讓它可以寫入內容 (包括 gh-pages 分支)
      pages: write    # 專門用於 GitHub Pages 的寫入權限
      id-token: write # 如果未來需要 OIDC (OpenID Connect) 身份驗證，也預先設定

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y年%m月%d日 %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Update date in HTML
        run: |
          sed -i "s|<span id=\"last-updated-date\">.*</span>|<span id=\"last-updated-date\">${{ steps.date.outputs.DATE }}</span>|g" ./footer.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' # 確保只在主分支上部署
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # 你的網站靜態檔案目錄，通常是倉庫根目錄
